services:
  app:
    image: symfony-app:v2
    container_name: app      
    volumes:
      - ./myapp:/app
    ports:
      - 8010:8000
    depends_on:
      - db
    networks:
      - app_network

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app_network

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - app_network

networks:
  app_network:
    driver: bridge